### ISSUE TITLE
Could not resolve Uno.UI.Svg error (after upgrading to Uno.SDK to 5.1.56)

### ISSUE THREAD

**Issue by formalist** [unoplatform/uno#15502]
### Current behavior

After upgrading to Uno.SDK to 5.1.56 on an existing project, I get this error during compilation:

Unhandled exception. System.Exception: Could not resolve Uno.UI.Svg   MyProject.Wasm C:\Users\user\.nuget\packages\uno.wasm.bootstrap\9.0.0-dev.27\build\Uno.Wasm.Bootstrap.targets   209

![image](https://github.com/unoplatform/uno/assets/17143426/aac9ad5d-88a5-4341-9f15-4c4c76e421df)

But if try to add the Uno.Ui.Svg package, i get the error:

UNOB0001 Cannot build with both Uno.WinUI and Uno.UI nuget packages referenced. 

(since I'm using Uno.WinUI.* packages) 

### Expected behavior

No compilation errors

### How to reproduce it (as minimally and precisely as possible)

The problem doesn't happen with a new project (dotnet new unoapp)

### Works on UWP/WinUI

None

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

5.1.56

### IDE

Visual Studio 2022

### IDE version

17.9.0

**Comment by jeromelaban** [comment]
Thanks. Uno.UI.Svg is the assembly name, regardless of Uno.UI of Uno.WinUI. In your case, you need Uno.UI.Svg.

**Comment by formalist** [comment]
> Thanks. Uno.UI.Svg is the assembly name, regardless of Uno.UI of Uno.WinUI. In your case, you need Uno.WinUI.Svg. Can you try with this package and see if it helps?

Same error. Actually, i was already using Uno.WinUI.Svg, and before upgrading to 5.1.56 it was compiling without errors.

**Comment by jeromelaban** [comment]
Thanks. You may be able to troubleshoot what happens by looking at the [binlog here](https://platform.uno/docs/articles/uno-builds-troubleshooting.html), attach it here as well. There may be an authoring error or a configuration error.

**Comment by formalist** [comment]
Thanks. I generated the binlog (attached), but can't figure out the issue...  

[msbuild.zip](https://github.com/unoplatform/uno/files/14337017/msbuild.zip)

**Comment by jeromelaban** [comment]
Thanks. Taking a look again at [the documentation](https://platform.uno/docs/articles/features/svg.html), it's not sufficiently explained that the uno.winui.svg package should not be included in the common class library.

The fix is to remove the package from the common class library, as well as removing it from the Wasm head (the browser is able to handle it properly without an additional library).
