### ISSUE TITLE
Win UI platform fails with TypeLoadException after Nuget upgrades

### ISSUE THREAD

**Issue by HakanL** [unoplatform/uno#10653]
### Current behavior

After upgrading to the latest dev build Uno 4.7.0-dev.529 I'm getting a TypeLoadException upon startup with this message:
`Cannot create instance of type 'Microsoft.UI.Xaml.Controls.XamlControlsResources' [Line: 10 Position: 40]`

If I go back to the latest stable version of Uno.WinUI, version 4.6.19 then I'm getting a bunch of build errors:

```
1>C:\Projects\Other\App7\App7.Shared\App.xaml.cs(14,39,14,50): error CS0433: The type 'Application' exists in both 'Microsoft.WinUI, Version=3.0.0.0, Culture=neutral, PublicKeyToken=de31ebe4ad15742b' and 'Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null'
1>C:\Projects\Other\App7\App7.Windows\obj\x64\Debug\net7.0-windows10.0.19041.0\App.g.i.cs(40,51,40,62): error CS0433: The type 'Application' exists in both 'Microsoft.WinUI, Version=3.0.0.0, Culture=neutral, PublicKeyToken=de31ebe4ad15742b' and 'Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null'
1>C:\Projects\Other\App7\App7.Shared\App.xaml.cs(16,17,16,23): error CS0433: The type 'Window' exists in both 'Microsoft.WinUI, Version=3.0.0.0, Culture=neutral, PublicKeyToken=de31ebe4ad15742b' and 'Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null'
1>C:\Projects\Other\App7\App7.Shared\App.xaml.cs(38,62,38,86): error CS0433: The type 'LaunchActivatedEventArgs' exists in both 'Microsoft.WinUI, Version=3.0.0.0, Culture=neutral, PublicKeyToken=de31ebe4ad15742b' and 'Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null'
1>C:\Projects\Other\App7\App7.Shared\App.xaml.cs(95,48,95,73): error CS0433: The type 'NavigationFailedEventArgs' exists in both 'Microsoft.WinUI, Version=3.0.0.0, Culture=neutral, PublicKeyToken=de31ebe4ad15742b' and 'Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null'
1>C:\Projects\Other\App7\App7.Shared\App.xaml.cs(107,50,107,69): error CS0433: The type 'SuspendingEventArgs' exists in both 'Microsoft.Windows.SDK.NET, Version=10.0.22621.24, Culture=neutral, PublicKeyToken=31bf3856ad364e35' and 'Uno, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null'
1>C:\Projects\Other\App7\App7.Shared\MainPage.xaml.cs(23,44,23,48): error CS0433: The type 'Page' exists in both 'Microsoft.WinUI, Version=3.0.0.0, Culture=neutral, PublicKeyToken=de31ebe4ad15742b' and 'Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null'
1>C:\Projects\Other\App7\App7.Windows\obj\x64\Debug\net7.0-windows10.0.19041.0\MainPage.g.i.cs(13,65,13,69): error CS0433: The type 'Page' exists in both 'Microsoft.WinUI, Version=3.0.0.0, Culture=neutral, PublicKeyToken=de31ebe4ad15742b' and 'Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null'
1>C:\Projects\Other\App7\App7.Windows\obj\x64\Debug\net7.0-windows10.0.19041.0\MainPage.g.i.cs(40,61,40,77): error CS0433: The type 'DependencyObject' exists in both 'Microsoft.WinUI, Version=3.0.0.0, Culture=neutral, PublicKeyToken=de31ebe4ad15742b' and 'Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null'
```

The reason I try to upgrade is to use features from the new UI Toolkit (ExtendedSplashScreen) in v2.4-dev.135.

### Expected behavior

Should build fine with 4.6.19, or should run fine with 4.7.0-dev.529.

### How to reproduce it (as minimally and precisely as possible)

https://github.com/HakanL/UnoSimpleApp

### Works on UWP/WinUI

None

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### Affected platforms

Windows

### IDE

Visual Studio 2022

### IDE version

17.4.2

**Comment by MartinZikmund** [comment]
@jeromelaban @kazo0  this is probably the same error we saw with toolkit?

**Comment by jeromelaban** [comment]
@HakanL Thanks for the report. This is happening because of net7.0. Try using net6.0 for now.

**Comment by HakanL** [comment]
@jeromelaban Ah, I see. I have some other dependencies that are currently on .NET 7, but is this a priority by the team, to get it working with .NET 7?

**Comment by jeromelaban** [comment]
Got it. 

On WinAppSDK, with Uno 4.7-dev (and without it), I originally got the same exception you got `Cannot create instance of type 'Microsoft.UI.Xaml.Controls.XamlControlsResources'`, but some reason I'm not getting it anymore. I downgraded to WinAppSDK 1.1.2, then upgraded again to 1.2.221116.1 and it worked. Very curious.

With regards to 4.6.19 not working with net7.0, we're backporting one specific PR from master, but you can otherwise use 4.7-dev in the meantime (given that you stop getting the WinAppSDK exception like I did...).

**Comment by jeromelaban** [comment]
This should now be fixed in 4.6 and 4.7-dev.

**Comment by HakanL** [comment]
Thank you @jeromelaban, I can confirm it works with .NET7 and dev-950 now!
