### PR TITLE
docs: Adjust wording in svg support

### LINKED ISSUE #15502: Could not resolve Uno.UI.Svg error (after upgrading to Uno.SDK to 5.1.56)
### Current behavior

After upgrading to Uno.SDK to 5.1.56 on an existing project, I get this error during compilation:

Unhandled exception. System.Exception: Could not resolve Uno.UI.Svg   MyProject.Wasm C:\Users\user\.nuget\packages\uno.wasm.bootstrap\9.0.0-dev.27\build\Uno.Wasm.Bootstrap.targets   209

image

But if try to add the Uno.Ui.Svg package, i get the error:

UNOB0001 Cannot build with both Uno.WinUI and Uno.UI nuget packages referenced. 

(since I'm using Uno.WinUI.* packages) 

### Expected behavior

No compilation errors

### How to reproduce it (as minimally and precisely as possible)

The problem doesn't happen with a new project (dotnet new unoapp)

### Workaround

_No response_

### Works on UWP/WinUI

None

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

5.1.56

### Affected platforms

_No response_

### IDE

Visual Studio 2022

### IDE version

17.9.0

### Relevant plugins

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by jeromelaban**
closes #15502

### CODE REVIEW

**Comment by jeromelaban** [comment]
@mergifyio backport release/stable/5.1

File: doc/articles/features/svg.md [hunk 1]
```diff
@@ -4,22 +4,22 @@ uid: Uno.Features.SVG
...
-* `SkiaSharp.Views.Uno.WinUI` (or `SkiaSharp.Views.Uno` if you are using a UWP-based app template).
+- `Uno.WinUI.Svg` (or `Uno.UI.Svg` if you are using a UWP-based app template)
+- `SkiaSharp.Views.Uno.WinUI` (or `SkiaSharp.Views.Uno` if you are using a UWP-based app template)
 
 > [!NOTE]
 > If the `Uno.[UI|WinUI].Svg` package is not installed, you will get a warning when an `.svg` image is loaded.
->
-> [!NOTE]
-> The `Uno.[UI|WinUI].Svg` package is not needed for WebAssembly.
+
```
Comment (Youssef1313) [inline doc/articles/features/svg.md:20]: Likely required by markdownlint. It should render the same either way.



```suggestion
>
```

**Review by ajpinedam — APPROVED** [review]
