### ISSUE TITLE
Uno.WindowsCommunityToolkit solution fails to compile with latest Uno due to resource errors

### ISSUE THREAD

**Issue by davidjohnoliver** [unoplatform/uno#1352]
## Repro steps

1. Clone the Uno.WindowsCommunityToolkit fork - https://github.com/unoplatform/Uno.WindowsCommunityToolkit
2. Update to latest Uno. (Easiest method is to do a search-and-replace for `Version="1.46.0-dev.1991"` with `Version="1.46.196-dev.2395"`)
3. Try to build the solution

## Current behavior
`Microsoft.Toolkit.Uwp.UI.Controls` and `Microsoft.Toolkit.Uwp.UI.Controls.DataGrid` projects faild to build for Uno targets with XAML compilation errors.

## Expected behavior

Solution builds.

## Notes

Sample errors:
```
4>obj\Debug\xamarinios10\g\XamlCodeGenerator\TabView_74937f1da8e19a29aced4812d73bf344.g.cs(416,102,416,136): error CS0117: 'GlobalStaticResources' does not contain a definition for 'TabViewItemHeaderRevealBorderBrush'
4>obj\Debug\xamarinios10\g\XamlCodeGenerator\RadialGauge_d6976e6207e9d6750c833b25be5ecfd0.g.cs(194,20,194,126): error CS0030: Cannot convert type 'Windows.UI.Xaml.Media.SolidColorBrush' to 'Windows.UI.Color'
```

The errors seem to all involve resources defined within `ResourceDictionary.ThemeDictionaries`. These regressions were probably introduced by https://github.com/unoplatform/uno/pull/1188.

## Environment

Nuget Package:

Package Version(s): 1.46.196-dev.2395

Affected platform(s):
- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- x ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by davidjohnoliver** [comment]
cc @carldebilly

**Comment by HaoLife** [comment]
I want to explain the problem, Uno WindowsCommunityToolkit cannot use in 1.45.0 version, he used to "theme".
All of the resources in the "ResourceDictionary.ThemeDictionaries" cannot be generated.
although "Uno. WindowsCommunityToolkit" compilation is successful, but he is unable to use, the runtime can't find the corresponding resources.


In the new version of "1.46.196-dev.2395" the problem is the "StaticResource" tag, such as

<StaticResource x:Key="TabViewItemHeaderBackground" ResourceKey="SystemControlTransparentBrush" />

He USES property access under GlobalStaticResources. This property cannot be generated.

**Comment by davidjohnoliver** [comment]
@HaoLife Thanks for the insights. :) Indeed, before the recent update, theme resources were just ignored completely. 

Now we're attempting to handle them, but in a way that doesn't work for the syntax in WCT. We'll address this.
