### PR TITLE
fix: [macOS] follow system colors changes

### LINKED ISSUE #6767: Uno Platform doesn't follow accent colour on macOS
## Current behavior
On macOS, SystemAccentColor is set to the hard-coded value - blue instead of using the user's accent colour selected in System Preferences.

## Expected behavior
SystemAccentColor should be set to the user's accent colour by default.

Screenshot 2021-08-14 at 12 48 12

Here's an example using NavigationView which doesn't apply the user's accent colour for the selection indicator.

Related to https://github.com/unoplatform/uno/issues/3555

### PR DESCRIPTION
**Pull request by iury-kc**
GitHub Issue (If applicable): closes #6767

## PR Type

What kind of change does this PR introduce?
 
- Bugfix 

## What is the current behavior?

Uno Apps were not able to detect custom color changes made by the user. 

## What is the new behavior?

Now, the app can detect the custom changes using using UISettings.ColorValuesChanged
and retry the colors by UISettings.GetColorValue().

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been added/updated which fit [documentation template](https://github.com/unoplatform/uno/blob/master/doc/.feature-template.md) (for bug fixes / features)
- [x] [Unit Tests and/or UI Tests](https://github.com/unoplatform/uno/blob/master/doc/articles/uno-development/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] Validated PR `Screenshots Compare Test Run` results.
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal) and uses the [automatic close keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue).
- [x] Commits must be following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) specification.

  
## Other information

Valid to know: AppKit doesn't have all UITypes available on uno. So, some are still hardcoded on SystemResources.xaml.

### CODE REVIEW

**Comment by iury-kc** [comment]
Just a comment: the test itself is testing only if the UISettings is giving the system colors itself. As there's not a easy way to simulate the system color changes.

File: src/Uno.UWP/UI/ViewManagement/UISettings.cs [hunk 1]
```diff
@@ -6,6 +6,9 @@
 using Uno.Helpers.Theming;
 using Windows.Foundation;
 using Windows.UI.Core;
+#if __MACOS__
+	using AppKit;
```
Comment (jeromelaban) [inline src/Uno.UWP/UI/ViewManagement/UISettings.cs:10]:
```suggestion
using AppKit; 
```

File: src/Uno.UWP/UI/ViewManagement/UISettings.cs [hunk 2]
```diff
@@ -53,13 +65,21 @@ public Color GetColorValue(UIColorType desiredColor)
...
 				UIColorType.Background =>
 					systemTheme == SystemTheme.Light ? Colors.White : Colors.Black,
 				UIColorType.Foreground =>
 					systemTheme == SystemTheme.Light ? Colors.Black : Colors.White,
 				// The accent color values match SystemResources.xaml in Uno.UI
 				// as we can't access Application resources from here directly.
 				UIColorType.Accent => Color.FromArgb(255, 51, 153, 255),
+#endif
+
 				UIColorType.AccentDark1 => Color.FromArgb(255, 0, 90, 158),
```
Comment (jeromelaban) [inline src/Uno.UWP/UI/ViewManagement/UISettings.cs:83]: We need to build those colors as well, I'll looking up the proper way to build those, I'll let you know.

**Review by jeromelaban — COMMENTED** [review]
This is looking good! The test is indeed not automatable for now, so validating that we're getting the same values is fine for now.

File: src/Uno.UWP/UI/ViewManagement/UISettings.cs [hunk 3]
```diff
@@ -53,13 +65,21 @@ public Color GetColorValue(UIColorType desiredColor)
 			var systemTheme = SystemThemeHelper.SystemTheme;
 			return desiredColor switch
 			{
+
+#if __MACOS__
+				UIColorType.Background => NSColor.ControlBackground,
+				UIColorType.Foreground => NSColor.ControlText,
+				UIColorType.Accent => NSColor.ControlAccent,
+#else
 				UIColorType.Background =>
```
Comment (MartinZikmund) [inline src/Uno.UWP/UI/ViewManagement/UISettings.cs:74]: I am not sure if this can't cause issues - I think some people use `UIColorType.Background` and `UIColorType.Foreground` to detect the current system theme, in which case they may compare directly against `Black` and `White` 🤔

Comment (jeromelaban) [reply src/Uno.UWP/UI/ViewManagement/UISettings.cs:74]: Indeed. We only need to change Accent, not the rest for now.

File: src/Uno.UWP/UI/ViewManagement/UISettings.cs (hunk 2 above)
Comment (jeromelaban) [reply src/Uno.UWP/UI/ViewManagement/UISettings.cs:83]: We're still gathering information on how to build those colors, I'll let you know when we have the correct inforation.

File: src/Uno.UWP/UI/ViewManagement/UISettings.cs (hunk 3 above)
Comment (iury-kc) [reply src/Uno.UWP/UI/ViewManagement/UISettings.cs:74]: I agree that to solve the issue, Accent is enough. However, I disagree to comparing black and white colors to detect the system theme, as user may customize the system colors.

**Comment by iury-kc** [comment]
Getting building errors from CI, but it builds on macOS ( Monterey 12.2.1):
image

Azure macOS / Xamarin version maybe???

**Comment by jeromelaban** [comment]
Interesting. It's likely that the Xamarin version we're using on CI is not recent enough to get this property. Let's bump it and see what happens.

**Comment by jeromelaban** [comment]
This is a very curious error, it even fails on net6:
```
C:\a\1\s\src\Uno.UI.RuntimeTests\Tests\Windows_UI\Given_Color.cs(75,76): error CS0117: 'NSColor' does not contain a definition for 'ControlAccentColor'
``
This is not an error that's coming from the version of VS. I'll pull the branch to test.

File: src/Uno.UI.RuntimeTests/Tests/Windows_UI/Given_Color.cs [hunk 4]
```diff
@@ -63,5 +63,25 @@ public static IEnumerable<object[]> GetCompare()
...
+#if __MACOS__
+		[TestMethod]
+		public async Task When_User_Change_macOS_System_Colors()
+		{
+			var _uiSettings = new Windows.UI.ViewManagement.UISettings();
+
+		  	Color SUT_1 = _uiSettings.GetColorValue(Windows.UI.ViewManagement.UIColorType.Accent);
+			Color SUT_2 = _uiSettings.GetColorValue(Windows.UI.ViewManagement.UIColorType.Background);
+
+			var accent = new Windows.UI.Xaml.Media.SolidColorBrush(AppKit.NSColor.ControlAccentColor).Color;
```
Comment (jeromelaban) [inline src/Uno.UI.RuntimeTests/Tests/Windows_UI/Given_Color.cs:75]: This is the right name:
```suggestion
			var accent = new Windows.UI.Xaml.Media.SolidColorBrush(AppKit.NSColor.ControlAccent).Color;
```

File: src/Uno.UI.RuntimeTests/Tests/Windows_UI/Given_Color.cs [hunk 5]
```diff
@@ -63,5 +63,25 @@ public static IEnumerable<object[]> GetCompare()
 			yield return new object[] { ColorHelper.FromArgb(0xFF, 0xFF, 0x7F, 0xFF), ColorHelper.FromArgb(0xFF, 0xFF, 0x7F, 0xFF), true };
 			yield return new object[] { ColorHelper.FromArgb(0xFF, 0xFF, 0xFF, 0x7F), ColorHelper.FromArgb(0xFF, 0xFF, 0xFF, 0x7F), true };
 		}
+#if __MACOS__
```
Comment (jeromelaban) [inline src/Uno.UI.RuntimeTests/Tests/Windows_UI/Given_Color.cs:66]: Let's enable the feature only on net6 and later for now. You'll need to do the same for the other blocks of this PR.

```suggestion
#if __MACOS__ && NET6_0_OR_GREATER
```

**Review by jeromelaban — APPROVED** [review]

**Comment by jeromelaban** [comment]
I've rebased your PR and removed the unnecessary bump in macOS CI version.

**Review by MartinZikmund — APPROVED** [review]
