### ISSUE TITLE
Issues when building Eto.Platform.WinUI

### ISSUE THREAD

**Issue by ris-work** [unoplatform/uno#20373]
### Current behavior

I'm trying to port Eto.Platform.WinUI to Platform.Uno as a backend instead of the Microsoft's one, so that I can have it work on top of WASM one day. All the other backends can be safely ignored as it has a native GTK# and has a native WPF backend too.
`System.NullReferenceException: 'Object reference not set to an instance of an object.'`
```Uno.UI.Dispatching.dll!Uno.UI.Dispatching.NativeDispatcher.GetHasThreadAccess() Line 19	C#
Uno.UI.Dispatching.dll!Uno.UI.Dispatching.NativeDispatcher.HasThreadAccess.get() Line 460	C#
Uno.UI.Dispatching.dll!Microsoft.UI.Dispatching.DispatcherQueue.GetForCurrentThread() Line 39	C#
Uno.UI.dll!Microsoft.UI.Xaml.ResourceDictionary.ResourceDictionary() Line 37	C#
Uno.UI.dll!Microsoft.UI.Xaml.Application.Application() Line 64	C#
Eto.Test.WinUI.dll!Eto.Test.WinUI.App.App() Line 32	C#
Eto.Test.WinUI.dll!Eto.Test.WinUI.App.Main.AnonymousMethod__3_0(Microsoft.UI.Xaml.ApplicationInitializationCallbackParams p) Line 58	C#
Uno.UI.dll!Microsoft.UI.Xaml.Application.StartPartial(Microsoft.UI.Xaml.ApplicationInitializationCallback callback) Line 97	C#
Uno.UI.dll!Microsoft.UI.Xaml.Application.Start(Microsoft.UI.Xaml.ApplicationInitializationCallback callback) Line 270	C#
Eto.Test.WinUI.dll!Eto.Test.WinUI.App.Main(string[] args) Line 57	C#
```

The program builds fine. When I open it, it shows the above error. I had to add a 
```cs
Microsoft.UI.Xaml.Application.Start(p => {
    var app = new App();
    app.InitializeComponent();
				
});
```
by myself as the program complained about the lack of a Main method.

This project had to be done like this as I cannot start a 'new' project (Eto.Forms itself is large).

This is a public, open source effort, and I have the repository [here](https://github.com/ris-work/Eto-WinForms-Native-Unix) in the branch `Platform.Uno`.

Thank you very much for your time and effort.

### Expected behavior

Eto.WinUI (nascent) tests starting and working

### How to reproduce it (as minimally and precisely as possible)

The repository mentioned should be sufficient, I think

### Works on UWP/WinUI

WinUI3

### Environment

Windows, dotnet 9

### Renderer

- [X] Skia
- [ ] Native

### Affected platforms

Windows

### IDE version

2022 preview

**Comment by MartinZikmund** [comment]
I notice that you are trying to add the Uno references in the existing WinUI project, instead it should be easier and more reliable to add a Blank Uno Platform project to the solution and then try to add the relevant files to it. This is because Uno Platform now uses a custom MSBuild SDK called Uno.Sdk which takes care of a large portion of the cross-platform magic

**Comment by ris-work** [comment]
> I notice that you are trying to add the Uno references in the existing WinUI project, instead it should be easier and more reliable to add a Blank Uno Platform project to the solution and then try to add the relevant files to it. This is because Uno Platform now uses a custom MSBuild SDK called Uno.Sdk which takes care of a large portion of the cross-platform magic

Thank you. I have made things almost build now, following your advice. However, I have received new errors:
```  
Eto net9.0-desktop failed with 1 error(s) (0.0s)
    C:\Program Files\dotnet\sdk\10.0.100-preview.3.25201.16\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(117,5): error NETSDK1139: The target platform identifier desktop was not recognized.
  Eto net9.0-browserwasm failed with 1 error(s) (0.0s)
    C:\Program Files\dotnet\sdk\10.0.100-preview.3.25201.16\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(117,5): error NETSDK1139: The target platform identifier browserwasm was not recognized.
  Eto net9.0-ios failed with 1 error(s) (0.0s)
    C:\Program Files\dotnet\sdk\10.0.100-preview.3.25201.16\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error NETSDK1005: Assets file 'C:\Users\Rishi\source\repos\eto2\artifacts\obj\Windows\Eto\project.assets.json' doesn't have a target for 'net9.0-ios'. Ensure that restore has run and that you have included 'net9.0-ios' in the TargetFrameworks for your project.
  Eto net9.0-android failed with 1 error(s) (0.0s)
    C:\Program Files\dotnet\sdk\10.0.100-preview.3.25201.16\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error NETSDK1005: Assets file 'C:\Users\Rishi\source\repos\eto2\artifacts\obj\Windows\Eto\project.assets.json' doesn't have a target for 'net9.0-android'. Ensure that restore has run and that you have included 'net9.0-android' in the TargetFrameworks for your project.
```

There is something I am missing. Eto.csproj itself is not platform-specific and should be just one target (AFAIU it does not do anything platform dependent _at all_). There should be _one_ target and that is _net9.0_ and the consumer project (Platform.Uno) tries to look for platform-specific versions that don't (and won't) exist. I tried looking up about how do I go forcing it to use net9.0 for all platforms but the potential solution (mentioned below) did not work.
I tried adding the following, running `dotnet clean`, `dotnet restore` and `dotnet build`:
```
  <PropertyGroup>
    <!-- Ensures that any consuming project will fall back to net9.0 assets -->
    <AssetTargetFallback>$(AssetTargetFallback);net9.0</AssetTargetFallback>
  </PropertyGroup>
```
It did not work and I am getting the same errors. Having a net9.0 in the consuming Platform.Uno project won't allow it to start. Please guide me about going further.

The source code for the Uno ClassLib:
`src\eto.winui\eto.winui.uno` at branch `Platform.Uno`
The source code for the Uno Tests project:
`test\eto.test.uno\eto.test.uno` at branch `Platform.Uno`
Repository: https://github.com/ris-work/Eto-WinForms-Native-Unix
(the default branch contains Eto.Forms port to [Core.System.Windows.Forms](https://github.com/DanielVanNoord/System.Windows.Forms) to facilitate a native-ish Cairo backend (WinForms) rendering on Unix-like platform and has nothing to do with Platform.Uno, GitHub doesn't allow two distinct named forks of the same project).


Thank you.

**Comment by ris-work** [comment]
Related: #13771 where fallbacks are mentioned, but however does not seem to have any solutions mentioned apart from altering the SDK to restore the default behaviour (which is falling back to `net9.0`).

**Comment by ris-work** [comment]
I have successfully made it build on `net9.0-desktop`, android and ios targets, and it is working Microsoft Windows (R) (I haven't tested on others). I ran into a strange problem on WebAssembly targets.
```
    C:\Users\Rishi\source\repos\eto2\test\Eto.Test.UWinUI\Eto.Test.UWinUI\obj\Debug\net9.0-browserwasm\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.BindableTypeProviders.BindableTypeProvidersSourceGenerator\BindableMetadata.g.cs(1294,85): error CS0434: The namespace 'System.Windows.Input.ICommand' in 'Eto.WinUI, Version=2.9.0.0, Culture=neutral, PublicKeyToken=null' conflicts with the type 'ICommand' in 'System.ObjectModel, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
    C:\Users\Rishi\source\repos\eto2\test\Eto.Test.UWinUI\Eto.Test.UWinUI\obj\Debug\net9.0-browserwasm\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.BindableTypeProviders.BindableTypeProvidersSourceGenerator\BindableMetadata.g.cs(1295,76): error CS0434: The namespace 'System.Windows.Input.ICommand' in 'Eto.WinUI, Version=2.9.0.0, Culture=neutral, PublicKeyToken=null' conflicts with the type 'ICommand' in 'System.ObjectModel, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
    C:\Users\Rishi\source\repos\eto2\test\Eto.Test.UWinUI\Eto.Test.UWinUI\obj\Debug\net9.0-browserwasm\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.BindableTypeProviders.BindableTypeProvidersSourceGenerator\BindableMetadata.g.cs(1330,260): error CS0434: The namespace 'System.Windows.Input.ICommand' in 'Eto.WinUI, Version=2.9.0.0, Culture=neutral, PublicKeyToken=null' conflicts with the type 'ICommand' in 'System.ObjectModel, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
    C:\Users\Rishi\source\repos\eto2\test\Eto.Test.UWinUI\Eto.Test.UWinUI\obj\Debug\net9.0-browserwasm\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.BindableTypeProviders.BindableTypeProvidersSourceGenerator\BindableMetadata.g.cs(1332,242): error CS0434: The namespace 'System.Windows.Input.ICommand' in 'Eto.WinUI, Version=2.9.0.0, Culture=neutral, PublicKeyToken=null' conflicts with the type 'ICommand' in 'System.ObjectModel, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

Is there any way to resolve this (by e.g. hiding one from the global usings)? I tried aliasing, didn't work. Since it is a generated file, I cannot control the behaviour by normal means (the other platforms are building okay). Please help me if you have the time and resources, I am this close to porting it to WASM.

**Comment by ris-work** [comment]
Ported, it works now. Thanks, @MartinZikmund .
https://github.com/user-attachments/assets/fb3c19d1-f260-45d7-bad2-82a09e3597d5
