### ISSUE TITLE
[WASM] ... no longer builds using latest DEV bits

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#12914]
### Current behavior

I'm not sure if caused by #12755 or not, but upgrading to latest DEV bits (see screenshot below) prevents my solution from building throwing these errors
```
9>C:\tmp\unusual-src-dev\Unusual.Wasm\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator\MaterialTheme_84d781f597680f94b23c291ff1c40a24.cs(1190,14,1190,108): error CS1029: #error: 'Property for DropDownPreferredPlacement cannot be found on Microsoft.UI.Xaml.Controls.ComboBox'
9>C:\tmp\unusual-src-dev\Unusual.Wasm\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator\MaterialTheme_84d781f597680f94b23c291ff1c40a24.cs(6125,15,6125,119): error CS1029: #error: 'Property for ShouldFallBackToNativeScrollBars cannot be found on Microsoft.UI.Xaml.Controls.ScrollViewer'
```

@TopProgrammer77 @dr1rrb 

<img width="1280" alt="image" src="https://github.com/unoplatform/uno/assets/26179242/e086115f-8145-43f6-9303-8c8216cdb573">

### Expected behavior

WASM should build

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
